### ISSUE TITLE
Is the "$regex" search operator implemented ?

### ISSUE THREAD

**Issue by DataHearth** [PoloDB/PoloDB#107]
Hey ! 

I just started using `PoloDB` and it works like a charm ! Great software and it's very intuitive 😄 .

I have a quick question. The [documentation](https://www.polodb.org/docs/curd/query#condition) specifies which search operator is implemented from the MongoDB engine (I guess it's the MongoDB engine). Does it includes the [$regex](https://www.mongodb.com/docs/manual/reference/operator/query/regex/) operator ?

I want to search for a specific pattern inside the DB with a simple pattern like 

```rust
{
"$regex": [{
  "name":  r".*name.*"g
}]
``` 

Thanks!

**Comment by vincentdchan** [comment]
Hi! This feature has not been implemented yet. However, if MongoDB implements it, I will add it to the roadmap. As I am currently working on implementing create_index, this will be considered a lower priority.

If you are interested, pull requests are also welcome.

**Comment by DataHearth** [comment]
@vincentdchan Hey! I started working on this feature on my free time ^^. But I'm quite lost with the codebase (firsttime with a big rust codebase ^^"). Do you know how I could debug the behavior of the evaluation on the `$regex` or any other query like evaluation ? 

At first glance, it seems that the `bson::bson::Regex` is translated to plain text and not interpreted/evaluated for this case.  

Thanks !

**Comment by vincentdchan** [comment]
Thanks for your interests! Implementing this is not a simple task, but I can provide you with some ideas.

1. Recognize `$regex` semantics in `polodb_core/vm/subprogram.rs`. You can try to understand the test `print_complex_print`.
2. Add an op to represents the regex tester in `polodb_core/vm/op.rs` 
3. Modify subprogram to compile your `regex` tester op.
4. Implement the new OP in `polodb_core/vm/vm.rs`
5. Add unit tests

Don't know if it would be too difficult for you. You can give it a try~

**Comment by DataHearth** [comment]
Thanks the tips! I'll give it a try 😄.
