### ISSUE TITLE
New Python binding

### ISSUE THREAD

**Issue by vincentdchan** [PoloDB/PoloDB#108]
Since the legacy binding is deprecated, needs a new binding

**Comment by DataHearth** [comment]
I can potentially create the python binding using either [PyO3](https://github.com/PyO3/pyo3) or [RustPython](https://github.com/RustPython/RustPython) if you're ok with that 🙂 .

**Comment by vincentdchan** [comment]
I just read this link: https://github.com/PyO3/pyo3/issues/435, and I think your disclosure is right. Let's use PyO3.

**Comment by Senhaji-Rhazi-Hamza** [comment]
Would be happy to help if the work starts regarding the python binding implementation ! (contact: hamza.senhajirhazi@gmail.com)

**Comment by michael-123123** [comment]
Hi - does anyone know if there is any progress on this issue?  @vincentdchan @DataHearth
