### ISSUE TITLE
Doc: help adding content to "Advanced condition" section

### ISSUE THREAD

**Issue by DataHearth** [PoloDB/PoloDB#116]
Hey! 

The [Advanced condition](https://www.polodb.org/docs/curd/query#advanced-condition) is missing some examples for other conditions. I can spend some time adding those.
But I don't see any repository in the `PoloDB` organization corresponding to the documentation of https://www.polodb.org/docs .

Do you accept contribution to the documentation ?

**Comment by vincentdchan** [comment]
Sure. The docs are in [this repo](https://github.com/vincentdchan/polodb-docs), and they are deployed on Vercel. Due to payment reasons, I can’t make it a repository under the org. However, PRs are welcome!

**Comment by vincentdchan** [comment]
The PR is merged.
