### ISSUE TITLE
No Database::open_file in wasm

### ISSUE THREAD

**Issue by dario-davi** [PoloDB/PoloDB#125]
Hi,

I saw you merged wasm feature into master, but if I run a quick test, using polodb_core = "4.4.0", I get the following compiler error: 

error[E0599]: no function or associated item named `open_file` found for struct `Database` in the current scope
  --> src/polo_repository/mod.rs:12:26
   |
12 |         return Database::open_file("resources.db").unwrap();
   |                          ^^^^^^^^^ function or associated item not found in `Database`

the code snippets is just: 

`use std::fs::File;
use std::io::BufReader;

use polodb_core::Database;
use serde::{Deserialize, Serialize};
use serde_json::Deserializer;

lazy_static! {
    pub static ref POLO_DB: Database = {
        println!("Initializing PoloDB");

        return Database::open_file("resources.db").unwrap();
    };
}

fn insert_json_to_polodb<T: for<'de> Deserialize<'de> + Serialize>(
    file_path: &str,
    collection_name: &str,
) {
    let collection = POLO_DB.collection(collection_name);
    let stream =
        Deserializer::from_reader(BufReader::new(File::open(file_path).unwrap())).into_iter::<T>();

    stream.for_each(|data| {
        collection.insert_one(data.unwrap()).unwrap();
    });
}`

**Comment by vincentdchan** [comment]
"open_file" is not supported on WASM version. I think [OPFS](https://web.dev/origin-private-file-system/) can be used as the file backend on WASM in the future, but more investigation is needed. Currently, IndexedDB will be used as the backend in the browser, which is still under development.

**Comment by vincentdchan** [comment]
The progress of IndexedDB backend can be tracked in #113

**Comment by vincentdchan** [comment]
The support of WASM will be removed. It's not maintained anymore.
