### ISSUE TITLE
Add `update_or_insert` operation

### ISSUE THREAD

**Issue by rektdeckard** [PoloDB/PoloDB#130]
It would be slick to have a `update_or_insert` (upsert) collection method that would take a query to uniquely identify a document, and the new or updated document. If the query matches an existing document, the document is updated with the new values provided, else it is created.

In my particular application, new and existing records are not so easy to tease apart, and fetched data includes a mix of both. I would rather not have to query the database for existing records, split the list, and perform both an `insert_many` and a number of `update_one` operations in a loop. I appreciate that transactions make this pretty trivial in terms of performance and consistency, but it would be a super nice convenience for an already very convenient crate. Having the `_many` version of this would be even better!

```rs
// impl<T>  Collection<T>
pub fn update_or_insert(&self, query: Document, upsert: Document) -> Result<UpdateOrInsertResult>;

// App
let mut session = db.start_session().unwrap();
session.start_transaction(None).unwrap();
 
let collection = db.collection::<Item>("items");
let new_and_updated: Vec<Item> = refresh_items().await?;

for item in new_and_updated {
  collection.update_or_insert(
    doc! { "guid": item.guid },
    bson::to_document(item).unwrap(),
  )?;
}
```

**Comment by vincentdchan** [comment]
Yes we need this. Will add this.

**Comment by vincentdchan** [comment]
We can use upsert now:
```
let update_result = col.update_one_with_options(
        doc! { "_id": 1 },
        doc! { "$set": { "name": "John", "age": 30 } },
        UpdateOptions::builder().upsert(true).build(),
    ).unwrap();
```

**Comment by rektdeckard** [comment]
Awesome, thanks!
