### ISSUE TITLE
Query by enum type

### ISSUE THREAD

**Issue by sayanb** [PoloDB/PoloDB#133]
I am storing records and one of the fields is an `Enum` type

```
pub enum Cuisine {
    French,
    Chinese,
    Thai,
    Japanese,
    Korean,
    Indian,
    Italian,
    Mexian,
    Turkish,
    Other(String),
}
```

There is no problem with the insertion. However, a query

```
let restaurants = collection.find(doc! {
        "cuisine": cuisine,
 })?;
```
 
 where `cuisine` is a variant of `Cuisine` type
 
 produces the following compiler error:
 
 ```
error[E0277]: the trait bound `Bson: From<Cuisine>` is not satisfied
 the trait `From<Cuisine>` is not implemented for `Bson`
```
 
 Is there a way to query by an `Enum` variant at all, or this is currently not possible without implementing `Display` trait for it, then converting it to a `String`?

**Comment by vincentdchan** [comment]
You can check the bson spec. Looks like the possible is to convert enum to number or string, it depends on you.

**Comment by vincentdchan** [comment]
Close due to no further responses
