### ISSUE TITLE
Crash and corrupt data base

### ISSUE THREAD

**Issue by greenpdx** [PoloDB/PoloDB#140]
I am using a axum server with a polodb_core backend.
axum = 0.7.1
polodb_core 4.4.0

The database keeps getting corrupted. About once a day, I get a crash.  I plan to do more testing including stress testing, but to get things started, this is what I know now.  

It started with
thread 'tokio-runtime-worker' panicked at /home/hydro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polodb_core-4.4.0/lsm/lsm_backend/lsm_file_backend.rs:180:9:
assertion failed: flag == format::LSM_INSERT || flag == format::LSM_POINT_DELETE

Code
    let coll: Collection<LTHP> = db.collection("lthp");
    let cnt =  coll.count_documents().unwrap();
    let sd = serde_json::to_string(data).expect("Bad Data");
    //let t = serde_json::from_value(data);
    //println!("{:?}", sd);
    let utc: DateTime<Utc> = Utc::now(); 
    let ts = utc.timestamp();
    let rslt = coll.insert_one(LTHP {
        id: cnt,
        ts: ts,
        bme280: data["bme280"].clone(),
        as7341: data["as7341"].clone(),
    });

**Comment by greenpdx** [comment]
I wrote a threaded rust program to write many inserts as fast as possible, I loop100 time with 10 threads and no crash.

BUT i do have a question. I open file and polodb creates that file and a file with .wal extension.  I understand that is a write on log file.  But the normal data file has 0 length and if I try to open it again I get NotAValidDatabase error.
How do I flush the log file to the regular file?

**Comment by vincentdchan** [comment]
Hey guys! @greenpdx 
PoloDB use [Rocks](https://github.com/facebook/rocksdb) as the storage layer now(after v5.0.0).
RocksDB is very solid. Theoretically PoloDb will be more robust.
Feel free to try the latest version and give me feedback!

**Comment by vincentdchan** [comment]
Close due to no further responses. Please reopen or submit a new issue if you have more questions.
