### ISSUE TITLE
Every time I cargo run, the polodb-librocksdb-sys needs to be recompiled

### ISSUE THREAD

**Issue by StudentWeis** [PoloDB/PoloDB#174]
Thank you for your work. I've been using PoloDB, which is an amazing library. However, I noticed that the compile time is quite long because polodb-librocksdb-sys always needs to be recompiled. How can I resolve this issue?

**Comment by StudentWeis** [comment]
After running `cargo clean`, the issue was resolved, so there's no need to trouble you further. Thanks again for your work!

**Comment by LearningProcesss** [comment]
In my case `cargo clean` does not solve the issue, building process stucks at  
`Building [=======================> ] 191/195: polodb-librocksdb-sys(build) `

Any tips?
