### ISSUE TITLE
Panic caused by overflow in VM::execute when using .skip() in query

### ISSUE THREAD

**Issue by dongbin86** [PoloDB/PoloDB#187]
I encountered a panic while running a query with polodb_core when using .skip() and .limit(). Here is the code that triggered the crash:
`let books = collection
    .find(doc! {})
    .skip(1)
    .limit(1)
    .run()?;
for book in books {
    println!("name: {:?}", book);
}
`
The following panic occurred:

`thread 'main' panicked at 'attempt to subtract with overflow', C:\Users\polly\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polodb_core-5.1.2\vm\vm.rs:948:46
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:662
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:74
   2: core::panicking::panic_const::panic_const_sub_overflow
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:181
   3: polodb_core::vm::vm::VM::execute
             at C:\Users\polly\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polodb_core-5.1.2\vm\vm.rs:948
`

polodb_core version: 5.1.2

**Comment by vincentdchan** [comment]
Will publish as `5.1.3`
