### ISSUE TITLE
Can not update collection UnknownUpdateOperation(...)

### ISSUE THREAD

**Issue by peepo5** [PoloDB/PoloDB#42]
```rs
collection
    .update(
        Some(&mk_document! { "_key": key_name }),
        &mk_document! { "value": value },
    )
    .unwrap();
```

```rs
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownUpdateOperation("value")', src/db.rs:143:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I want to update the entry with the "_key" as key_name's value field, however, it displays the above error. any help?

**Comment by vincentdchan** [comment]
You need to specific the update operation, so try:
```
collection
    .update(
        Some(&mk_document! { "_key": key_name }),
        &mk_document! {
          "$set": &mk_document! {
             "value": value
          }
       },
    )
```

Other operation can be found at `docs/en-US/Update.md`

**Comment by vincentdchan** [comment]
Are you saying using collection again or using database again?

It's designed to be allow using collection for multiple times.
Database is designed to be used multiple times too, but limited. Only one instance can read/write database at the same time. Otherwise, the thread will be locked.

**Comment by peepopoggers** [comment]
Just out of curiosity, is it an issue with database initiation or collection initiation?
