### ISSUE TITLE
[Suggestion]: Index Implementation

### ISSUE THREAD

**Issue by lmtr0** [PoloDB/PoloDB#54]
Hello there, good day!
There is [this very cool talk](https://www.youtube.com/watch?v=HubezKbFL7E) I found online about text searching in rust. However, I also found 2 implementations of search libraries that also implement indexes:
- https://docs.rs/tantivy/latest/tantivy/ <- this one is more mature and has more feature
- https://docs.rs/noise_search/latest/noise_search/

I'm not very familiar with the project, so I think it will be difficult for me to implement this feature right now, but as I saw that there is no implementation yet, so I figure I would research a little about the topic to see if I find something useful for you!

Also, there is another implementation of an embedded database for C# called [LiteDB](https://www.litedb.org/docs/indexes/), and they have an explanation on their index implementation. Btw, their implementation is based on [this](https://www.youtube.com/watch?v=kBwUoWpeH_Q) video.

**Comment by vincentdchan** [comment]
Thank you very much. I will read the data you provided.
But recently I have had no time for this project. So maybe later.

**Comment by lmtr0** [comment]
Not a problem for me, I want to get involved in this project, I'm just not with time right now! But I wanted to share the suggestions I found :)

**Comment by vincentdchan** [comment]
If you want to contribute, you can ask any question directly. I will reply ASAP.

**Comment by lmtr0** [comment]
Thanks

**Comment by lmtr0** [comment]
Is it open or closed, I'm confused

**Comment by vincentdchan** [comment]
I am implementing this issue and it is very close to completion. It was mistakenly closed, so I have reopened it again.

**Comment by lmtr0** [comment]
I understand now, thank you

**Comment by lmtr0** [comment]
Got it, sounds great

**Comment by vincentdchan** [comment]
The latest release `v4.3.0` supports creating indexes(alpha testing). It's not stable. But you can give it a try if you are interested.

I have added [docs](https://www.polodb.org/docs/advanced/indexes) for the index implementation. Enjoy it.

**Comment by lmtr0** [comment]
I will thx

**Comment by vincentdchan** [comment]
To make the issue list clearer, I am going to close this issue as it has been completed. If you meet any problems, please feel free to create new issues.
