### ISSUE TITLE
Query on Nested Document

### ISSUE THREAD

**Issue by bigbass1997** [PoloDB/PoloDB#90]
While it is possible to insert a document containing nested documents into a collection, it doesn't appear possible to use them in queries. Meaning it's impossible to filter documents by a nested value. I initially encountered this when trying to filter by an enum containing variants with fields (as Bson serializes them as nested documents).

Here I have written a minimal example of what I mean, using just a struct inside another struct:
```Rust
#[derive(Debug, PartialEq, Serialize, Deserialize)]
struct Example {
    inner: Inner,
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
struct Inner {
    data: String,
}

let example = Example { inner: Inner { data: "foobar".into() } };

let db = Database::open_memory().unwrap();
let col: Collection<Example> = db.collection("test");

col.insert_one(&example).unwrap();

let found1 = col.find_one(None).unwrap().unwrap();
assert_eq!(example, found1);

// create query document using the data we just read from the database
let query = polodb_core::bson::to_document(&found1).unwrap();

let found2 = col.find_one(query).unwrap(); // panics, find_one() returns Err
assert_eq!(Some(found1), found2);
```
For reference, the Bson-serialized `example` data looks like this:
```Bson
Document({
    "inner": Document({
        "data": String("foobar")
    })
})
```
The error returned from the last `.find_one()` operation:
```
InvalidField(InvalidFieldStruct { field_type: "query", field_name: "data", path: Some("/inner/data") })
```
_MongoDB reference [Query on Embedded/Nested Documents](https://www.mongodb.com/docs/manual/tutorial/query-embedded-documents/)_

---
Additionally, if I instead use mongodb's [dot notation](https://www.mongodb.com/docs/manual/core/document/#dot-notation) for the query:
```Rust
let query = doc! {
    "inner.data": "foobar"
};
let found2 = col.find_one(query).unwrap();
assert_eq!(Some(found1), found2); // panics, found2 is None
```
This `find_one()` operation no longer returns an error, but it also doesn't return any data.

**Comment by bigbass1997** [comment]
I did figure out a temporary workaround though.. You can retrieve the entire collection as a `Vec<Document>`, manually filter, and get the document(s)'s ObjectId. Then use that to perform whatever update/delete operations you want. Not ideal, but it works.
```Rust
let matches: Vec<(ObjectId, Example)> = db.collection::<Document>("test")
    .find_many(None)
    .unwrap()
    .into_iter()
    .filter_map(|doc| {
        let id = doc.get_object_id("_id").unwrap();
        
        from_document::<Example>(doc)
            .ok()
            .map(|entry| (id, entry))
    })
    .filter(|(_, entry)| entry.inner.data == "foobar") // example filtering with nested data
    .collect();

let (id, example) = matches[0].clone();
assert_eq!(
    Some(example),
    db.collection::<Example>("test")
        .find_one(doc! {
            "_id": id
        }).unwrap()
);
```

**Comment by vincentdchan** [comment]
Sure, nested queries should be supported. I will start thinking about how to implement them.

**Comment by vincentdchan** [comment]
`4.3.1` supports querying embedded documents now. Try it if you are still interested.

The `.` form is the right way to use it:

```rust
let query = doc! {
    "inner.data": "foobar"
};
```
